# Site settings
title: Always SWERVING to steer free of obstacles
email: x75@domain.com
description: "x75's experimental blog and general meme dump."
baseurl: ""
url: "http://x75.github.io"
twitter_username: x7557x
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

comments: true

