# Site settings
title: Always SWERVING to steer free of classically-minded mobs
email: x75@domain.com
description: "x75's blog, a dump for memes and sketches"
baseurl: ""
url: "http://x75.github.io"
twitter_username: x7557x
github_username:  x75

# Build settings
markdown: kramdown
hard_wrap: false
permalink: pretty

comments: true

