# Site settings
title: Navigating option landscapes
email: opt X sdfk x de
description: "Mission log from climbing mount improbable by Oswald Berthold (x75)"
baseurl: ""
# url: "https://x75.github.io"
url: "https://dynatrop.es"
twitter_username: x7557x
github_username:  x75

# Build settings
markdown: kramdown
hard_wrap: false
permalink: pretty

comments: true

