---

layout: post\\
title: Catalogue of sound and music works by Oswald Berthold\\
comments: true\\
tags: sound music algorithms generative-models sequence-models dsp synthesis sonfication data-driven-audio digital-musician aesthetics-ng\\
---

** Catalogue of sound and music works by Oswald Berthold
   :PROPERTIES:
   :CUSTOM_ID: catalogue-of-sound-and-music-works-by-oswald-berthold
   :END:

*Keywords*: sound, music, algorithms, generative models, sequence
models, dsp, synthesis, sonfication, data-driven audio, digital
musician, aesthetics-ng, ...

*** Humboldt beginnings and plazma
    :PROPERTIES:
    :CUSTOM_ID: humboldt-beginnings-and-plazma
    :END:

Not showing specific musical talent during childhood, Oswald's musical
career starts at age 6 or so, with the production of nonsense radio
plays together with his brother /ub/ using the tape-based recording
functions of their parents' stereo. Later on, playing the guitar had
to be learned, to be able to found a band together with homies Klaus,
grt, Tomi, Mitch and Hannah. After a few transformations, this band
became /plazma/ which was a unique outfit within the ecosystem of
teenage bands in the city of Graz, Austria, at that time. plazma
has two albums, both self-produced at ultra-low budget, using advanced
track-bouncing techniques and countryside creativity retreats. Both
also, unfortunately unreleased to date, but #wip.

*Update*: plazma's debut album self-published on music cassette (MC) in
1994 is available digitally for the first time ever on [[https://plazmagraz.bandcamp.com/releases][plazma's bandcamp]].

*** farmersmanual
    :PROPERTIES:
    :CUSTOM_ID: farmersmanual
    :END:

Separate story to be filled in at another time, until then find more
info on [[https://farmersmanual.bandcamp.com/][bandcamp]], [[https://www.discogs.com/artist/356-Farmers-Manual][discogs]], [[https://en.wikipedia.org/wiki/Farmers_Manual][wikipedia]], and their [[http://web.fm][website]] or the [[http://rla.web.fm][recent
live archive]] or the [[https://archive.org/search.php?query=farmersmanual][internet archive]].

*** cd\_slopper
    :PROPERTIES:
    :CUSTOM_ID: cd_slopper
    :END:

Working together with [[http://florianhecker.blogspot.com/][Florian Hecker]] we soon thought [[https://www.discogs.com/artist/11328-CD_slopper][cd\_slopper]] to be
a good name for our activity. At the time we were deep in exploring
codecs and manipulating audio on the level of non-PCM codecs. The
frame structure used in MP3 is aesthetically very close to grain based
synthesis. This became an interesting set of relations to sample from.

*** fals.ch
    :PROPERTIES:
    :CUSTOM_ID: fals.ch
    :END:

At about the same time that work on cd\_slopper was started, we built
a new version of Mego's sublabel falsch on [[https://web.archive.org/web/19991218005216/http://fals.ch][fals.ch]]. The idea was to be
a digital content provider (aka netlabel), build a random but unique
self-referential and novel digital style, and implement the
organization as a digital process itself. Curiosly, the backend of the
first version of the website was Andrew Pam's (?, check) perl
implementation of Ted Nelson's ZigZag(tm) using custom frontend
code. In the second iteration, a custom implementation of a similar
mechanism was used, making it easier to benefit from existing web
technologies and allowing online editing of the label's datastore,
directly via the website. All of this proved to be creatively fruitful
and a lot of fun, although economically unsuccessful due to our
outright art-pour-l'art approach, aka business naivity. The label
released more than 50 packages of digital audio-visual content by a
diverse set of upcoming and acclaimed artists, united by the their
quest for truly innovative approaches to media design of technical and
aesthetic excellence. The releases include two tangible CDROMs serving
as cross-sections of the catalogue.

*** gullibloon
    :PROPERTIES:
    :CUSTOM_ID: gullibloon
    :END:

Picking up fm's sonification and real time data-driven synthesis and
composition approach, gullibloon was conceived as both software vendor
and musical identity, building all of their pieces on data feeds
collected from virtual and physical source processes such as network
traffic, computer activity status, various sensors and algorithmic
generators. They can be found on the [[https://gullibloon.org][web]].

-  Gullibloon 'MUH' (ALKU 87, 2010), Music cassette tape, grey and pink
   versions, sold out,
   [[http://alkualkualkualkualkualkualkualkualkualku.org/pmwiki/pmwiki.php/Main/ALKU87]]
-  army of darkness, on
   [[https://www.youtube.com/watch?v=a7nEPDXEioM&t=28s][youtube]],
   produced ca. 2010 (?)

*** Solo work
    :PROPERTIES:
    :CUSTOM_ID: solo-work
    :END:

Been working on different synthetic persona over time including
/calimba de luna/, /dprmkr/, /pxp/ and /tsx/.

-  dprmkr - Test codes for the measurement of airborne noise, (con*,
   1997)
-  Farmers Manual attribution is incorrect
-  pxp - while (wavetrap, 2002)
-  pxp - nada (rekorder, 2005)
-  Various - Rara avis, ALKU, 2017?
-  tsx - recur (trust, 2017), available via TRUST Vienna on
   [[https://trust.bandcamp.com/album/recur][bandcamp]] or on youtube ([[https://www.youtube.com/watch?v=K6gjx773udo][going]], [[https://www.youtube.com/watch?v=lSqJ-OmqtDA][squrp]], [[https://www.youtube.com/watch?v=-MyBKmX7xpA][slow]], [[https://www.youtube.com/watch?v=oEtSrK6kbO4][brum brum like]]).

** Raw list
   :PROPERTIES:
   :CUSTOM_ID: raw-list
   :END:

FIXME: include trackdb, in the meantime simple version

| *Year* | *artist*        | *package*                                        | *Refs*                      |
|--------+-----------------+--------------------------------------------------+-----------------------------|
|   1996 | farmersmanual   | fm                                               | Mego - Mego 017             |
|   1996 | farmersmanual   | No backup                                        | Mego - Mego 008             |
|   1996 | farmersmanual   | does not compute                                 | tray - TRAY 1               |
|   1997 | farmersmanual   | fsck                                             | tray - TRAY 2, OR - SLUMP 8 |
|   1997 | calimba de luna | test codes for the measurement of airborne noise | constar - con* 0004         |
|   1998 | farmersmanual   | explorers\_we                                    | OR - SQUISH04               |
|   2000 | cd\_slopper     | SaskieWoxi                                       | OR - JODEL 10               |
|   2002 | pxp             | while(p){print"."," "x$p++}                      | Wavetrap - WAV04            |
|   2003 | farmersmanual   | Recent live archive (RLA)                        | Mego - Mego 777             |
|   2004 | Emanual Frakt   | Kekkoushougai                                    | Tonto - tonto #24           |
|   2005 | pxp             | nada                                             | Dekorder - Dekorder 009     |
|   2010 | gullibloon      | MUH                                              | Alku - ALKU 87              |
|   2016 | Various         | Rara Avis                                        | Alku - ALKU 99              |
|   2017 | farmersmanual   | fmoto                                            | generate and test - gt0     |
|   2017 | tsx             | recur                                            | TRUST - TRUSTe02            |

#+BEGIN_HTML
  <!--
  References: autopop, augmented creativity, augmented editing,
  teaching, game sounds, sonification, information sound scapes.
  -->
#+END_HTML

#+BEGIN_HTML
  <!-- {% include archive.html %} -->
#+END_HTML

** Comments
   :PROPERTIES:
   :CUSTOM_ID: comments
   :END:

{% if page.comments %}
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//x75.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endif %}

** Footnotes
   :PROPERTIES:
   :CUSTOM_ID: footnotes
   :END:

@@html:<sup>@@@@html:<a id="fn.1" href="#fnr.1">@@1@@html:</a>@@@@html:</sup>@@fn.1
